import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#00315d",
        "surface-container-low": "#161b29",
        "tertiary-fixed": "#6ffbbe",
        "outline": "#8c909f",
        "primary-fixed": "#d8e2ff",
        "on-tertiary-container": "#00311f",
        "on-surface-variant": "#c2c6d6",
        "error": "#ffb4ab",
        "secondary": "#a4c9ff",
        "on-surface": "#dee2f5",
        "tertiary": "#4edea3",
        "on-primary-fixed": "#001a42",
        "on-secondary-container": "#d6e5ff",
        "surface-container-highest": "#303443",
        "surface-container": "#1a1f2d",
        "surface-dim": "#0e1320",
        "secondary-container": "#0267b8",
        "surface-container-lowest": "#090e1b",
        "outline-variant": "#424754",
        "secondary-fixed": "#d4e3ff",
        "on-primary": "#002e6a",
        "inverse-on-surface": "#2b303e",
        "on-primary-fixed-variant": "#004395",
        "background": "#0e1320",
        "on-error-container": "#ffdad6",
        "on-background": "#dee2f5",
        "surface-variant": "#303443",
        "surface-tint": "#adc6ff",
        "primary-container": "#4d8eff",
        "surface-bright": "#343948",
        "error-container": "#93000a",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary": "#003824",
        "on-error": "#690005",
        "primary": "#adc6ff",
        "tertiary-container": "#00a572",
        "secondary-fixed-dim": "#a4c9ff",
        "on-secondary-fixed": "#001c39",
        "on-primary-container": "#00285d",
        "surface-container-high": "#252a38",
        "inverse-surface": "#dee2f5",
        "surface": "#0e1320",
        "on-secondary-fixed-variant": "#004883",
        "on-tertiary-fixed": "#002113",
        "inverse-primary": "#005ac2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      keyframes: {
        bounce: {
          "0%, 60%, 100%": { transform: "translateY(0)" },
          "30%": { transform: "translateY(-8px)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        pop: {
          "0%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.15)" },
          "100%": { transform: "scale(1)" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        dotBounce: {
          "0%, 60%, 100%": { transform: "translateY(0)" },
          "30%": { transform: "translateY(-6px)" },
        },
      },
      animation: {
        bounce: "bounce 1.4s infinite ease-in-out",
        float: "float 3s ease-in-out infinite",
        pop: "pop 0.4s ease-in-out",
        fadeIn: "fadeIn 0.4s ease-out forwards",
        dot1: "dotBounce 1.4s infinite ease-in-out 0s",
        dot2: "dotBounce 1.4s infinite ease-in-out 0.2s",
        dot3: "dotBounce 1.4s infinite ease-in-out 0.4s",
      },
      backdropBlur: {
        xl: "30px",
        "2xl": "40px",
      },
    },
  },
  plugins: [],
};

export default config;
